# Generated by Django 6.0.2 on 2026-03-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_remove_match_away_team_remove_match_home_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['number']},
        ),
        migrations.RenameField(
            model_name='round',
            old_name='deadline',
            new_name='lockout_time',
        ),
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.IntegerField(),
        ),
    ]
