# Generated by Django 6.0.2 on 2026-03-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_round_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='margin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
